language: c

compiler:
  - gcc
  - clang

install:
  # Need other repos for e.g. libuv-dev
  - sudo apt-add-repository -y ppa:linuxjedi/ppa
  - sudo apt-get update -qq
  # for unit tests
  - sudo apt-get install -y check
  # for static code analysis
  - sudo apt-get install -y cppcheck rats
  # for libuv
  - sudo apt-get install -y libuv-dev
  # for OpenSSL
  - sudo apt-get install -y libssl-dev
  # for test code coverage
  - sudo apt-get install -y lcov
  - gem install coveralls-lcov
  # for cmake
  - cmake

before_script:
  - cd ${TRAVIS_BUILD_DIR}
  - lcov --directory . --zerocounters

script:
  # - find . -type f -name "*.c" -print | grep -v t\/ | xargs cppcheck 2>&1
  # - find . -type f -name "*.c" -print | grep -v t\/ | xargs rats --language=c
  - git clone --depth 10 https://github.com/datastax/cpp-driver.git
  - mkdir -p cpp-driver/build
  - cd cpp-driver/build
  - cmake ..
  - make
  - sudo make install
  - cd ../../
  - git clone --depth 10 https://github.com/proftpd/proftpd.git
  - cp mod_sql_cassandra.c proftpd/contrib/
  - cd proftpd
  - ./configure --enable-dso --enable-tests --with-shared=mod_sql:mod_sql_cassandra
  - make
  - make clean
  - ./configure --enable-tests --with-modules=mod_sql:mod_sql_cassandra
  - make
