name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: '11 1 * * 0'

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      cassandra:
        # Docker Hub image
        image: bitnami/cassandra:4.0
        env:
          CASSANDRA_HOST: cassandra

    env:
      CASSANDRA_HOST: cassandra

    strategy:
      matrix:
        compiler:
          - clang
          - gcc
        container:
          - almalinux:8
          - alpine:3.18
          - ubuntu:22.04

    container: ${{ matrix.container }}

    steps:
      - name: Checkout ProFTPD
        uses: actions/checkout@v3
        with:
          repository: proftpd/proftpd
          path: proftpd

      - name: Checkout module source code
        uses: actions/checkout@v3
        with:
          path: proftpd-mod_sql_cassandra

      - name: Whitespace check
        if: ${{ matrix.container == 'ubuntu:22.04' }}
        run: |
          apt-get update -qq
          apt-get install -y git
          cd proftpd-mod_sql_cassandra
          if [[ -n $(git diff --check HEAD^) ]]; then
            echo "You must remove whitespace before submitting a pull request"
            echo ""
            git diff --check HEAD^
            exit 1
          fi

      - name: Prepare module source code
        run: |
          cp proftpd-mod_sql_cassandra/mod_sql_cassandra.c proftpd/contrib/

      - name: Install Alpine packages
        if: ${{ matrix.container == 'alpine:3.18' }}
        run: |
          apk update
          # for builds
          apk add bash build-base clang compiler-rt gcc make zlib-dev
          # for unit tests
          apk add check check-dev subunit subunit-dev

          # for Cassandra support
          apk add cassandra-cpp-driver-dev

          # for debugging
          clang --version
          gcc --version

      - name: Install RPM packages
        env:
          CPP_DRIVER_VERSION: 2.17.1
        if: ${{ matrix.container == 'almalinux:8' }}
        run: |
          # Need to add other repos for e.g. libsodium
          yum install -y dnf-plugins-core epel-release yum-utils clang gcc make zlib-devel
          dnf config-manager --enable epel
          dnf config-manager --set-enabled powertools
          # for unit tests
          yum install -y check-devel https://cbs.centos.org/kojifiles/packages/subunit/1.4.0/1.el8/x86_64/subunit-1.4.0-1.el8.x86_64.rpm https://cbs.centos.org/kojifiles/packages/subunit/1.4.0/1.el8/x86_64/subunit-devel-1.4.0-1.el8.x86_64.rpm

          # for Cassandra support; see
          #  https://docs.datastax.com/en/developer/cpp-driver/2.17/topics/installation/
          yum install -y openssl-devel krb5-devel zlib-devel libuv
          yum install -y https://downloads.datastax.com/cpp-driver/centos/8/cassandra/v$CPP_DRIVER_VERSION/cassandra-cpp-driver-$CPP_DRIVER_VERSION-1.el8.x86_64.rpm
          yum install -y https://downloads.datastax.com/cpp-driver/centos/8/cassandra/v$CPP_DRIVER_VERSION/cassandra-cpp-driver-devel-$CPP_DRIVER_VERSION-1.el8.x86_64.rpm

          # for debugging
          clang --version
          gcc --version

      - name: Install Ubuntu packages
        env:
          CPP_DRIVER_VERSION: 2.17.1
          DEBIAN_FRONTEND: noninteractive
          TZ: UTC
        if: ${{ matrix.container == 'ubuntu:22.04' }}
        run: |
          apt-get update -qq
          # for builds
          apt-get install -y clang gcc make
          # for unit tests
          apt-get install -y check libsubunit-dev

          # for Cassandra support; see
          #  https://docs.datastax.com/en/developer/cpp-driver/2.17/topics/installation/
          apt-get install -y curl libssl-dev libkrb5-dev libuv1-dev zlib1g
          curl -sLO https://datastax.jfrog.io/artifactory/cpp-php-drivers/cpp-driver/builds/2.17.1/e05897d/ubuntu/22.04/cassandra/v2.17.1/cassandra-cpp-driver_2.17.1-1_amd64.deb
          dpkg -i cassandra-cpp-driver_$CPP_DRIVER_VERSION-1_amd64.deb
          curl -sLO https://datastax.jfrog.io/artifactory/cpp-php-drivers/cpp-driver/builds/2.17.1/e05897d/ubuntu/22.04/cassandra/v2.17.1/cassandra-cpp-driver-dev_2.17.1-1_amd64.deb
          dpkg -i cassandra-cpp-driver-dev_$CPP_DRIVER_VERSION-1_amd64.deb

          # for integration/regression test
          apt-get install -y \
            libcompress-raw-zlib-perl \
            libdata-dumper-simple-perl \
            libdatetime-perl \
            libfile-copy-recursive-perl \
            libfile-path-tiny-perl \
            libfile-spec-native-perl \
            libjson-perl \
            libnet-inet6glue-perl \
            libnet-ssh2-perl \
            libnet-ssleay-perl \
            libnet-telnet-perl \
            libposix-2008-perl \
            libtest-unit-perl \
            libtime-hr-perl \
            libwww-perl

          # for test code coverage
          apt-get install -y lcov ruby
          gem install coveralls-lcov

          # for HTML validation
          apt-get install -y tidy

          # for cqlsh
          apt-get install -y curl software-properties-common
          add-apt-repository -y ppa:deadsnakes/ppa
          apt-get install -y python3.9 python3.9-venv
          curl -s https://bootstrap.pypa.io/get-pip.py -o get-pip.py
          python3.9 get-pip.py
          pip3 --version
          pip3 install cqlsh
          cqlsh --version

          # for debugging
          clang --version
          gcc --version

      - name: Prepare code coverage
        if: ${{ matrix.container == 'ubuntu:22.04' }}
        run: |
          lcov --directory proftpd --zerocounters

      - name: Build as static module
        env:
          CC: ${{ matrix.compiler }}
        run: |
          cd proftpd
          ./configure LIBS="-lm -lsubunit -lrt -pthread" --enable-devel=coverage --enable-tests --with-modules=mod_sql:mod_sql_cassandra
          make

      - name: Install as static module
        run: |
          cd proftpd
          make install

      - name: Run integration tests
        if: ${{ matrix.compiler == 'gcc' && matrix.container == 'ubuntu:22.04' }}
        env:
          PROFTPD_TEST_BIN: /usr/local/sbin/proftpd
          PROFTPD_TEST_DIR: ${{ github.workspace }}/proftpd
        run: |
          cd proftpd-mod_sql_cassandra
          cqlsh -u cassandra -p cassandra -f t/etc/modules/mod_sql_cassandra/user.cql cassandra 9042
          cqlsh -u proftpd -p developer -f t/etc/modules/mod_sql_cassandra/keyspace.cql cassandra 9042
          perl tests.pl

      - name: Build as shared module
        env:
          CC: ${{ matrix.compiler }}
        run: |
          cd proftpd
          make clean
          ./configure LIBS="-lm -lsubunit -lrt -pthread" --enable-devel --enable-dso --with-shared=mod_sql:mod_sql_cassandra
          make

      - name: Install as shared module
        run: |
          cd proftpd
          make install

      - name: Check HTML docs
        run: |
          cd proftpd-mod_sql_cassandra
          echo "Processing mod_sql_cassandra.html"
          tidy -errors -omit -q mod_sql_cassandra.html | exit 0
